version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: motolocation-db
    environment:
      POSTGRES_USER: mottu
      POSTGRES_PASSWORD: mottu_password
      POSTGRES_DB: motolocation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: